server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mssecurity
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: ms-security

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework: INFO
